#!/bin/bash
konversi () {
read –p “Konversi Rupiah Ke- “  t
		case $t in
“dollar”) read –p “Masukan jumlah uang :” x;;
“pound”) read –p “Masukan jumlah uang :” y;;
“riyal”) read –p “Masukan jumlah uang :” z;;
*) echo “Tidak Tersedia”;;
		esac
			if (($x))
				then
				let hasil=$x/$1
				echo=”$hasil Dollar”
			elif (($y))
				then
				let hasil=$y/$2
				echo=”$hasil Pound”
			elif (($z))
				then
				let hasil=$z/$3
				echo=”$hasil Riyal”
			else
			echo “Maaf yang anda masukan salah”
			fi
}
konversi 14035 18333 3742 
